name: flutter_posui_pocket
description: "Aplazo Merchant App"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  webview_flutter: ^4.2.2
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.7
  provider: ^6.0.5
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  get_it: ^7.6.0
  intl: ^0.19.0
  masked_text: ^1.1.2
  mask_text_input_formatter: ^2.4.0
  dio: ^5.3.3
  pretty_dio_logger: ^1.3.1
  build_runner: ^2.4.6
  faker: ^2.1.0
  uuid: ^4.4.0
  mobile_scanner: ^5.1.1
  infinite_scroll_pagination: ^4.0.0
  shared_preferences: ^2.2.0
  currency_text_input_formatter: ^2.1.10
  video_player: ^2.7.0
  multi_masked_formatter: ^1.0.0
  maps_launcher: ^2.2.0
  flutter_fgbg: ^0.3.0
  keyboard_dismisser: ^3.0.0
  lottie: ^3.1.2
  permission_handler: ^11.3.1
  app_settings: ^5.0.0
  in_app_review: ^2.0.6
  fluttertoast: ^8.2.2
  encrypt: ^5.0.3
  skeletonizer: ^1.3.0
  flow_builder: ^0.1.0
  formz: ^0.7.0
  json_annotation: ^4.9.0
  url_launcher_platform_interface: ^2.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logo/
    - assets/images/alerts/
    - assets/images/commons/
    - assets/images/connectivity/
    - assets/lotties/
    - assets/gifs/
    - rsa_keys/

  fonts:
    - family: NewSpirit
      fonts:
        - asset: fonts/newspirit/newspirit_semibold.ttf
          weight: 700
        - asset: fonts/newspirit/newspirit_regular.ttf
          weight: 300
    - family: Manrope
      fonts:
        - asset: fonts/manrope/manrope_bold.ttf
          weight: 700
        - asset: fonts/manrope/manrope_semibold.ttf
          weight: 600
        - asset: fonts/manrope/manrope_regular.ttf
          weight: 300

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
